
local LSM = LibStub("LibSharedMedia-3.0")

-- -----
--   FONT
-- -----
LSM:Register("font", "Accidental Presidency", 		[[Interface\Addons\NeavUI\nMedia\nFonts\Accidental Presidency.ttf]])
LSM:Register("font", "Adventure",					[[Interface\Addons\NeavUI\nMedia\nFonts\Adventure.ttf]])
LSM:Register("font", "Alba Super", 					[[Interface\Addons\NeavUI\nMedia\nFonts\ALBAS___.ttf]])
LSM:Register("font", "Arm Wrestler", 				[[Interface\Addons\NeavUI\nMedia\nFonts\ArmWrestler.ttf]])
LSM:Register("font", "Atarian System",				[[Interface\Addons\NeavUI\nMedia\nFonts\SFAtarianSystem.ttf]])
LSM:Register("font", "Bazooka",						[[Interface\Addons\NeavUI\nMedia\nFonts\Bazooka.ttf]])
LSM:Register("font", "Black Chancery",				[[Interface\Addons\NeavUI\nMedia\nFonts\BlackChancery.ttf]])
LSM:Register("font", "Blazed", 						[[Interface\Addons\NeavUI\nMedia\nFonts\Blazed.ttf]])
LSM:Register("font", "Boris Black Bloxx", 			[[Interface\Addons\NeavUI\nMedia\nFonts\BorisBlackBloxx.ttf]])
LSM:Register("font", "Boris Black Bloxx Dirty", 	[[Interface\Addons\NeavUI\nMedia\nFonts\BorisBlackBloxxDirty.ttf]])
LSM:Register("font", "Collegiate", 					[[Interface\Addons\NeavUI\nMedia\nFonts\COLLEGIA.ttf]])
LSM:Register("font", "Covington",					[[Interface\Addons\NeavUI\nMedia\nFonts\SFCovington.ttf]])
LSM:Register("font", "Diogenes", 					[[Interface\Addons\NeavUI\nMedia\nFonts\DIOGENES.ttf]])
LSM:Register("font", "Disko", 						[[Interface\Addons\NeavUI\nMedia\nFonts\Disko.ttf]])
LSM:Register("font", "DorisPP",						[[Interface\Addons\NeavUI\nMedia\nFonts\DORISPP.ttf]])
LSM:Register("font", "Enigmatic",					[[Interface\Addons\NeavUI\nMedia\nFonts\Enigma__2.ttf]])
LSM:Register("font", "Express Freeway",				[[Interface\Addons\NeavUI\nMedia\nFonts\ExpressFreeway.ttf]])
LSM:Register("font", "Fitzgerald",					[[Interface\Addons\NeavUI\nMedia\nFonts\Fitzgerald.ttf]])
LSM:Register("font", "Frakturika Spamless", 		[[Interface\Addons\NeavUI\nMedia\nFonts\FRAKS___.ttf]])
LSM:Register("font", "Gentium",						[[Interface\Addons\NeavUI\nMedia\nFonts\Gentium.ttf]])
LSM:Register("font", "Hooked Up",					[[Interface\Addons\NeavUI\nMedia\nFonts\HookedUp.ttf]])
LSM:Register("font", "Impact", 						[[Interface\Addons\NeavUI\nMedia\nFonts\impact.ttf]])
LSM:Register("font", "Liberation Serif", 			[[Interface\Addons\NeavUI\nMedia\nFonts\LiberationSerif-Regular.ttf]])
LSM:Register("font", "Liberation Sans",				[[Interface\Addons\NeavUI\nMedia\nFonts\LiberationSans.ttf]])
LSM:Register("font", "Movie Poster",				[[Interface\Addons\NeavUI\nMedia\nFonts\SFMoviePoster-Bold.ttf]])
LSM:Register("font", "Mystic Orbs", 				[[Interface\Addons\NeavUI\nMedia\nFonts\MystikOrbs.ttf]])
LSM:Register("font", "Number",						[[Interface\Addons\NeavUI\nMedia\nFonts\fontNumber.ttf]])
LSM:Register("font", "Pokemon Solid", 				[[Interface\Addons\NeavUI\nMedia\nFonts\Pokemon Solid.ttf]])
LSM:Register("font", "Rock Show Whiplash", 			[[Interface\Addons\NeavUI\nMedia\nFonts\Rock Show Whiplash.ttf]])
LSM:Register("font", "Solange", 					[[Interface\Addons\NeavUI\nMedia\nFonts\Solange.ttf]])
LSM:Register("font", "Small",						[[Interface\AddOns\NeavUI\nMedia\nFonts\fontSmall.ttf]])
LSM:Register("font", "Star Cine", 					[[Interface\Addons\NeavUI\nMedia\nFonts\starcine.ttf]])
LSM:Register("font", "swf!t",						[[Interface\Addons\NeavUI\nMedia\nFonts\swfit.ttf]])
LSM:Register("font", "Thick",						[[Interface\Addons\NeavUI\nMedia\nFonts\fontThick.ttf]])
LSM:Register("font", "Trashco", 					[[Interface\Addons\NeavUI\nMedia\nFonts\trashco.ttf]])
LSM:Register("font", "Ubuntu Condensed", 			[[Interface\Addons\NeavUI\nMedia\nFonts\Ubuntu-C.ttf]])
LSM:Register("font", "Ubuntu Light", 				[[Interface\Addons\NeavUI\nMedia\nFonts\Ubuntu-L.ttf]])
LSM:Register("font", "Visitor",						[[Interface\Addons\NeavUI\nMedia\nFonts\fontVisitor.ttf]])
LSM:Register("font", "Vera Serif",					[[Interface\Addons\NeavUI\nMedia\nFonts\VeraSe.ttf]])
LSM:Register("font", "Waltograph UI", 				[[Interface\Addons\NeavUI\nMedia\nFonts\waltographUI.ttf]])
LSM:Register("font", "Wonder Comic",				[[Interface\Addons\NeavUI\nMedia\nFonts\SFWonderComic.ttf]])
LSM:Register("font", "X360", 						[[Interface\Addons\NeavUI\nMedia\nFonts\X360.ttf]])
LSM:Register("font", "Yanone Kaffeesatz Regular", 	[[Interface\Addons\NeavUI\nMedia\nFonts\YanoneKaffeesatz-Regular.ttf]])
LSM:Register("font", "Yellowjacket",				[[Interface\Addons\NeavUI\nMedia\nFonts\YELLOWJACKET.ttf]])
-- -----
--   SOUND
-- -----
LSM:Register("sound", "Warning", 					[[Interface\Addons\NeavUI\nMedia\nSounds\Warning.mp3]])
